### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Oevind** [Botster/plugin.video.liveleak#1]
Kodi 19 addons and scripts that have updated to support Python3 (and no longer support Python2)

**Comment by Botster** [comment]
I am not sure what you are saying. Are you saying that Kodi 19 will no longer support Python2 and therefore addons and scripts must support Python3? What exactly is the issue?

**Comment by Oevind** [comment]
Hi,

plugin.video.liveleak crashes under LibreELEC V19
   

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named html.entities
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.liveleak/default.py", line 6, in <module>
                                                from bs4 import BeautifulSoup as bs
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/builder/__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/dammit.py", line 14, in <module>
                                                from html.entities import codepoint2name
                                            ImportError: No module named html.entities
                                            -->End of Python script error report<--
2019-11-07 18:58:37.927 T:1156   ERROR: GetDirectory - Error getting plugin://plugin.video.liveleak/
2019-11-07 18:58:37.939 T:1040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.liveleak/) failed

**Comment by Botster** [comment]
Thank you for providing the exception report. It is quite helpful.

Kodi 19 is currently in Alpha state, and I am eager to see this issue resolved early on. However, this appears to be a LibreELEC/BeautifulSoup issue.

See: https://forum.kodi.tv/showthread.php?tid=342682&pid=2842061#pid2842061
And: https://forum.kodi.tv/showthread.php?tid=343068

If you file a bug report with them, please kindly post the link here so anyone interested can follow along with the resolution of the issue. Thank you.

**Comment by Botster** [comment]
Assumed resolved.
