### ISSUE TITLE
Only "Featured" category not displaying videos

### ISSUE THREAD

**Issue by vecnar** [Botster/plugin.video.liveleak#4]
Hello,

Featured videos are not showing today, the rest are working including search. I checked the kodi forum post but no info about it so i decided to post here.
I am using version1.4.2 and below is the output from the log after accessing featured category.

`2020-10-14 20:47:19.278 T:5996   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 492, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 401, in index
                                                (url, liz) = buildListItem(item)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 233, in buildListItem
                                                cmd = cmd.format( buildUrl( {'mode': 'label_user', 'user': credit} ) )
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 119, in buildUrl
                                                return BASE_URL + '?' + urlencode(query)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib.py", line 1343, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-10-14 20:47:19.323 T:1708   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26featured%3d1%26page%3d1
2020-10-14 20:47:19.330 T:6424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26featured%3d1%26page%3d1) failed
`

Let me know if you would like me to test anything.

Thank you,

Oleg

**Comment by Botster** [comment]
Thank you for reporting that.

If I am correct in what I suspect is causing that, you could also experience it in other categories as well. I need to take some time to ensure the fix won't break something else. I'm on it.

By the way, what version of Kodi are you using?

**Comment by vecnar** [comment]
Thank you for looking into this.

I have just tried to access each category from kodi and all except "featured" are listing videos and i am able to play them where featured do no list the videos. I am using kodi version 18 on old windows 7 64 bit os, i have also tried on android on the phone and on amazon fire tv stick and it is the same.
`Starting Kodi (18.4 Git:20190831-3ade758ceb). Platform: Windows NT x86 64-bit`

**Comment by vecnar** [comment]
Hello,
Just a quick update on the issue, as you pointed out it is not category specific. I was able to see page 1 in the morning but not page 2 but now i can also see page 2 but not page 3 so it has to be with some video description or something on page 3. I thought to make a screenshot of page 2 in case it helps you to identify which video has characters that are causing below error
`2020-10-16 11:55:32.309 T:5796   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 492, in <module>
                                                if url: index(url)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 401, in index
                                                (url, liz) = buildListItem(item)
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 233, in buildListItem
                                                cmd = cmd.format( buildUrl( {'mode': 'label_user', 'user': credit} ) )
                                              File "C:\Users\oleg\AppData\Roaming\Kodi\addons\plugin.video.liveleak\default.py", line 119, in buildUrl
                                                return BASE_URL + '?' + urlencode(query)
                                              File "C:\Program Files\Kodi\system\python\Lib\urllib.py", line 1343, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 3: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-10-16 11:55:32.359 T:2792   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26featured%3d1%26page%3d3
2020-10-16 11:55:32.385 T:4484   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.liveleak/?mode=indx&url=browse%3fa%3dlist%26featured%3d1%26page%3d3) failed`
![liveleakPage2](https://user-images.githubusercontent.com/44214918/96251029-ba086700-0fa7-11eb-9d0a-18622f7e6538.jpg)

**Comment by Botster** [comment]
Thank you for that additional information.

I haven't been able to duplicate the issue, but I am sure it is due to characters in a LL user's name that do not fit within the ASCII character set. I have edited the code so as to prevent Kodi from choking on such characters.

Since I have not yet run across one of these types of names since the previous update, I intend to give a few more days for testing before I issue a pull request to the Kodi repo. If are of a mind to, please download the plugin from Code button on the main page (https://github.com/Botster/plugin.video.liveleak) and see if it works better for you.

**Comment by vecnar** [comment]
Thank you for making changes. 
Before update i couldn't see videos when trying to access page 5 under featured category. After updating it worked and i took a screenshot of page 5 in case it is off any benefit.
![LiveleakPage5](https://user-images.githubusercontent.com/44214918/96353696-650f4280-10c6-11eb-9999-4111fb5a8b2d.jpg)

**Comment by Botster** [comment]
I think you are correct that it was the Writer on that particular video that the plugin could not handle.

With the helpful information you provided, I was able to successfully test it by going to Page 5 of the Featured category and finding that video. I now consider the issue fixed and will be issuing a pull request within the next few days.

Thank you!

**Comment by vecnar** [comment]
Glad that it helped and sorry for giving incorrect issue title

**Comment by Botster** [comment]
Not a problem. There was still an issue that needed to be looked at. I'm glad you reported it.
